### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by RomanOrlovskiy** [kubernetes-sigs/aws-load-balancer-controller#3214]
**Describe the bug**

ALB ingress pods are in a CrashLopp with the following error in logs after upgrading EKS to version 1.27:

```
{"level":"info","ts":"2023-05-26T16:47:22Z","msg":"version","GitVersion":"v2.5.1","GitCommit":"06abaed66e17a411ba064f34e6018b889780ac66","BuildDate":"2023-04-17T22:36:53+0000"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7fc579770850]

goroutine 1 [running]:
k8s.io/client-go/discovery.convertAPIResource(...)
	/go/pkg/mod/k8s.io/client-go@v0.26.3/discovery/aggregated_discovery.go:114
k8s.io/client-go/discovery.convertAPIGroup({{{0x0, 0x0}, {0x0, 0x0}}, {{0xc00005e3f0, 0x15}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...})
	/go/pkg/mod/k8s.io/client-go@v0.26.3/discovery/aggregated_discovery.go:95 +0x6f0
k8s.io/client-go/discovery.SplitGroupsAndResources({{{0xc0001381e0, 0x15}, {0xc0003d8e60, 0x1b}}, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...})
	/go/pkg/mod/k8s.io/client-go@v0.26.3/discovery/aggregated_discovery.go:49 +0x125
k8s.io/client-go/discovery.(*DiscoveryClient).downloadAPIs(0xc0005d21a0?)
	/go/pkg/mod/k8s.io/client-go@v0.26.3/discovery/discovery_client.go:328 +0x3de
k8s.io/client-go/discovery.(*DiscoveryClient).GroupsAndMaybeResources(0xc0005d25d0?)
	/go/pkg/mod/k8s.io/client-go@v0.26.3/discovery/discovery_client.go:203 +0x65
k8s.io/client-go/discovery.ServerGroupsAndResources({0x7fc57afcb480, 0xc0002c2810})
	/go/pkg/mod/k8s.io/client-go@v0.26.3/discovery/discovery_client.go:413 +0x59
k8s.io/client-go/discovery.(*DiscoveryClient).ServerGroupsAndResources.func1()
	/go/pkg/mod/k8s.io/client-go@v0.26.3/discovery/discovery_client.go:376 +0x25
k8s.io/client-go/discovery.withRetries(0x2, 0xc0005445e8)
	/go/pkg/mod/k8s.io/client-go@v0.26.3/discovery/discovery_client.go:651 +0x71
k8s.io/client-go/discovery.(*DiscoveryClient).ServerGroupsAndResources(0x0?)
	/go/pkg/mod/k8s.io/client-go@v0.26.3/discovery/discovery_client.go:375 +0x3a
k8s.io/client-go/restmapper.GetAPIGroupResources({0x7fc57afcb480?, 0xc0002c2810?})
	/go/pkg/mod/k8s.io/client-go@v0.26.3/restmapper/discovery.go:148 +0x42
sigs.k8s.io/controller-runtime/pkg/client/apiutil.NewDynamicRESTMapper.func1()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/client/apiutil/dynamicrestmapper.go:94 +0x25
sigs.k8s.io/controller-runtime/pkg/client/apiutil.(*dynamicRESTMapper).setStaticMapper(...)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/client/apiutil/dynamicrestmapper.go:130
sigs.k8s.io/controller-runtime/pkg/client/apiutil.NewDynamicRESTMapper(0xc000527560?, {0x0, 0x0, 0x201?})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/client/apiutil/dynamicrestmapper.go:110 +0x182
sigs.k8s.io/controller-runtime/pkg/cluster.setOptionsDefaults.func1(0xc00051f8f0?)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/cluster/cluster.go:217 +0x25
sigs.k8s.io/controller-runtime/pkg/cluster.New(0xc0002c4b40, {0xc0005d2f90, 0x1, 0x0?})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/cluster/cluster.go:159 +0x18d

```
**Steps to reproduce**
EKS version: 1.27
ALB ingress controller helm chart: 1.5.2

**Expected outcome**
The pods should start properly

**Environment**

* AWS Load Balancer controller version: 1.5.2 helm chart
* Kubernetes version: 1.27
* Using EKS (yes/no), if so version?: Yes

**Additional Context**:
Should be related to the following:
- https://github.com/kubernetes/kubernetes/pull/116603
- https://github.com/elastic/cloud-on-k8s/issues/6848

**Comment by oliviassss** [comment]
@RomanOrlovskiy were the LBC pods running well before the k8s upgrade and suddenly crashed after the k8s upgrade? Would you be able to share more info like the current LBC manifest, and k8s version before the upgrade?

**Comment by orsenthil** [comment]
@RomanOrlovskiy , do you have any aggregated servers (like promethus-adapter) in your cluster when you did an upgrade?

**Comment by RomanOrlovskiy** [comment]
@oliviassss the pods were running properly before the upgrade. It was done from EKS 1.25 to 1.27, and only on 1.27 the issues started to appear. Faced the same issue with ECK operator, but was able to resolve it by updating to the latest 2.8.0 version.

@orsenthil yes, we do have prometheus-adapter running in the cluster.

**Comment by orsenthil** [comment]
@RomanOrlovskiy , there is an upstream issue with promethus-adapter https://github.com/kubernetes-sigs/prometheus-adapter/issues/581 , which can return a malformed metric and cause the client-go to crash, and it is affecting other clients too. Please see if disabling or uninstalling it until the adapter issue is fixed.

**Comment by RomanOrlovskiy** [comment]
@orsenthil, appreciate your help. Scaling down prom-adapter helped in this case.
